# Generated by Django 4.2.19 on 2025-02-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='Approved',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='Body',
        ),
    ]
